[versions]
android-gradle-plugin = "9.0.0"
jgit = "7.5.0.202512021534-r"
json = "20251224"

[libraries]
# Build script
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
jgit-archive = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.archive", version.ref = "jgit" }
json = { group = "org.json", name = "json", version.ref = "json" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
